def mix(secret, value):
    return secret ^ value

def prune(secret):
    return secret % 16777216

def generate_secret_numbers(initial_secret, n=2000):
    secret = initial_secret
    for _ in range(n):
        secret = prune(mix(secret, secret * 64))
        secret = prune(mix(secret, secret // 32))
        secret = prune(mix(secret, secret * 2048))
    return secret

def read_input(filename):
    with open(filename, 'r') as file:
        return [int(line.strip()) for line in file]

def main():
    input_file = 'day22-input.txt'  # Change this to your input data file
    initial_secrets = read_input(input_file)
    total_sum = sum(generate_secret_numbers(secret) for secret in initial_secrets)
    print(f'Sum of the 2000th secret number generated by each buyer: {total_sum}')

if __name__ == '__main__':
    main()
